// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehgtdjuuzepumgpgowwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZ3RkanV1emVwdW1ncGdvd3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTk5MDIsImV4cCI6MjA1OTEzNTkwMn0.bpmdpuvwdv7WSeWOZKHSkN4MctMMDoXy582YEZT4HXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);